### ISSUE TITLE
Feature request: replace source

### ISSUE THREAD

**Issue by axelson** [tmbb/ex_code_gen#2]
Maybe this isn't in the scope/vision of the library but the way I'd like to use the library is to have code that user doesn't need to write but is generated (and regenerated) into the user's module.

Of course the tricky part of this would be to identify where the code block stops and starts, often in similar systems that's done with long comments (e.g. `# CODEGEN_BLOCK_f1/1_START`).

Is this something that could be interesting for this library? If not then maybe I'll just need to regenerate the whole module/file manually.

**Comment by tmbb** [comment]
> Maybe this isn't in the scope/vision of the library but the way I'd like to use the library is to have code that user doesn't need to write but is generated (and regenerated) into the user's module.

I don't understand what you mean. If the user doesn't have to edit the module code, why should it be generated? If you want to generate code you don't want to edit, you already have "traditional" (?) mix generators. The goal here is not ho have code that doesn't need to be edit.

> Is this something that could be interesting for this library? If not then maybe I'll just need to regenerate the whole module/file manually.

If I understand you correctly, then no, I am not interested in adding this

**Comment by axelson** [comment]
> I don't understand what you mean. If the user doesn't have to edit the module code, why should it be generated? If you want to generate code you don't want to edit, you already have "traditional" (?) mix generators. The goal here is not ho have code that doesn't need to be edit.

I'm toying with a library that would cut down on the boilerplate needed to use https://github.com/dashbitco/mox. Currently you have to write the same function names three times (once for the behaviour `@callback`, once for the implementation, and once for a "wrapper module" that just does something like `def call_api(args), do: impl().call_api(args`), the library would remove the need to manually write the "wrapper module". I was thinking about code generation for the wrapper module to allow the user to use go-to-definition in their editor to get to the default implementation.

But it does indeed seem out of scope, thank you for your time and consideration!
